from crewai import Agent, LLM
from crewai_tools import TavilySearchTool
import os
from dotenv import load_dotenv
load_dotenv()
import google.generativeai as genai

gemini_api_key = os.getenv('GEMINI_API_KEY')

llm = LLM(
    model='gemini/gemini-1.5-flash-latest',
    temperature=0.6,
    api_key=gemini_api_key,
    max_output_tokens=32768   
)

tavily_api_key = os.getenv('TAVILY_API_KEY')
tavily_search = TavilySearchTool(api_key=tavily_api_key)

quiz_agent = Agent(
    role = 'Quiz Generation agent',
    goal = 'Generate high-quality, structured, and engaging quizzes based on the provided topic'
            'and the detailed explanation generated by the content_search_agent, ensuring accuracy, relevance, clarity, and balanced difficulty levels.',
    backstory= ('A highly experienced senior educator and assessment designer who specializes in creating interactive and accurate quizzes.'
                'Uses both the provided topic and the researched content from the content_search_agent to design quizzes that are relevant, well-structured, and factually correct.'
                'Ensures the questions cover key concepts, maintain a balanced difficulty, and help learners strengthen their understanding.'),
    llm = llm,
    tools = [tavily_search],
    verbose = True,
    allow_delegation=False,
    always_respond=True 
)